version: 2.1

executors:
  docker-in-docker:
    docker:
      - image: docker:stable

  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

jobs:
  build-image:
    parameters:
      image-name:
        type: string
      build-dir:
        type: string
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: layers-<< parameters.image-name >>
      - run:
          name: restore image cache
          command: |
            docker load < layer-cache-<< parameters.build-dir >>.tar || true
      - run:
          name: build
          command: |
            docker build -t << parameters.image-name >> ./<< parameters.build-dir >>
      - run:
          name: login
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: push
          command: |
            docker push << parameters.image-name >>
      - run:
          name: save layers
          command: |
            docker save $(docker images -q) > layer-cache-<< parameters.build-dir >>.tar
      - save_cache:
          key: layers-<< parameters.image-name >>
          paths:
            - layer-cache-<< parameters.build-dir >>.tar

  deploy:
    executor: docker-in-docker
    steps:
      - run:
          name: auth
          command: |
            mkdir certs
            echo $DOCKER_CLIENT_KEY > certs/key.pem
            echo $DOCKER_CLIENT_CERT > certs/cert.pem
            echo $DOCKER_CA_CERT > certs/ca.pem
      - run:
          name: stop container
          environment:
            DOCKER_CERT_PATH: ./certs
            DOCKER_HOST: tcp://ptpb-aio.instance.buhman.org:2376
            DOCKER_TLS_VERIFY: 1
          command: |
            # systemd handles the rest of the restart chain
            docker stop pb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-image:
          name: build-image-pb
          image-name: ptpb/pb
          build-dir: pb
      - build-image:
          name: build-image-varnish
          image-name: ptpb/varnish
          build-dir: varnish
      - build-image:
          name: build-image-openresty
          image-name: ptpb/openresty
          build-dir: openresty
      - deploy:
          requires:
            - build-image-pb
            - build-image-varnish
            - build-image-openresty
