version: 2.1

executors:
  docker-in-docker:
    docker:
      - image: docker:stable

  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

jobs:
  build-image:
    parameters:
      image-name:
        type: string
      build-dir:
        type: string
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: |
            docker build -t << parameters.image-name >> ./<< parameters.build-dir >>
      - run:
          name: login
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: push
          command: |
            docker push << parameters.image-name >>

  deploy:
    executor: gcloud
    steps:
      - run:
          name: auth
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set compute/zone us-central1-c
            gcloud config set project crucial-baton-168900
      - run:
          name: service restart
          command: |
            gcloud compute ssh instance-ptpb-aio -- systemctl restart pb.service
            gcloud compute ssh instance-ptpb-aio -- systemctl restart varnish.service
            gcloud compute ssh instance-ptpb-aio -- systemctl restart openresty.service

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-image:
          name: build-image-pb
          image-name: ptpb/pb
          build-dir: pb
      - build-image:
          name: build-image-varnish
          image-name: ptpb/varnish
          build-dir: varnish
      - build-image:
          name: build-image-openresty
          image-name: ptpb/openresty
          build-dir: openresty
      - deploy:
          requires:
            - build-image-pb
            - build-image-varnish
            - build-image-openresty
