version: 2.1

executors:
  docker-in-docker:
    docker:
      - image: docker:stable

  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

jobs:
  build-image:
    parameters:
      image-name:
        type: string
      build-dir:
        type: string
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: |
            docker build -t << parameters.image-name >> ./<< parameters.build-dir >>
      - run:
          name: login
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: push
          command: |
            docker push << parameters.image-name >>

  deploy:
    executor: docker-in-docker
    environment:
      DOCKER_CERT_PATH: ./certs
      DOCKER_HOST: tcp://ptpb-aio.instance.buhman.org:2376
      DOCKER_TLS_VERIFY: 1
    steps:
      - run:
          name: auth
          command: |
            mkdir certs
            echo $DOCKER_CLIENT_KEY > certs/key.pem
            echo $DOCKER_CLIENT_CERT > certs/cert.pem
            echo $DOCKER_CA_CERT > certs/ca.pem

            # such hack, much wow
            sed -i 's/----- /-----\n/g;s/ -----/\n-----/g' certs/key.pem certs/cert.pem certs/ca.pem
      - run:
          name: pull
          command: |
            docker pull ptpb/pb
            docker pull ptpb/varnish
            docker pull ptpb/openresty
      - run:
          name: stop
          command: |
            # systemd handles the rest of the restart chain
            docker stop pb
      - run:
          name: prune
          command: |
            docker image prune -f
            docker container prune -f

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-image:
          name: build-image-pb
          image-name: ptpb/pb
          build-dir: pb
      - build-image:
          name: build-image-varnish
          image-name: ptpb/varnish
          build-dir: varnish
      - build-image:
          name: build-image-openresty
          image-name: ptpb/openresty
          build-dir: openresty
      - deploy:
          requires:
            - build-image-pb
            - build-image-varnish
            - build-image-openresty
